---
- id: "1713118932"
  alias: Ring Keypad Alarm
  description: Allow a Ring Keypad to control the Alarm entity
  use_blueprint:
    path: allenporter/ring_keypad_alarm.yaml
    input:
      keypad_device: DEVICE_ID
      keypad_entity: event.device_name_button
      alarm_entity: alarm_control_panel.security
      arming_delay: 50
      pending_delay: 45
