---
- id: "1687836340268"
  alias: Ring Keypad Mode
  description: "Update the Ring Keypad mode based on Alarm Control Panel state"
  use_blueprint:
    path: allenporter/ring_keypad_mode.yaml
    input:
      keypad_device: DEVICE_ID
      alarm_entity: alarm_control_panel.security
      arm_away_delay: 50
      trigger_delay: 45
