---
blueprint:
  name: Allow the Ring Keypad to control an Alarm Control Panel
  description: |
    Automations to connect the Ring Keypad Event Entity to send commands to
    an Alarm Control Panel.
    See https://github.com/allenporter/home-assistant-ring-keypad/
  domain: automation
  input:
    keypad_entity:
      name: Ring Keypad Entity
      description: The Ring Keypad event entity
      selector:
        entity:
          domain: event
          integration: ring_keypad
    alarm_entity:
      name: Alarm Control Panel entity
      description: The Alarm Control Panel to synchronize the keypad with
      selector:
        entity:
          domain: alarm_control_panel
mode: queued # Don't overload keypad
trace:
  stored_traces: 10
trigger:
  - platform: state
    entity_id: !input keypad_entity
condition:
  condition: state
  entity_id: !input keypad_entity
  attribute: event_type
  state:
    - alarm_disarm
    - alarm_arm_away
    - alarm_arm_home
action:
  - service: "alarm_control_panel.{{ trigger.to_state.attributes.event_type }}"
    data:
      entity_id: !input alarm_entity
      code: >
        {% if trigger.to_state.attributes.code != none %}
          {{ trigger.to_state.attributes.code }}
        {% endif %}
    continue_on_error: True
